### PR TITLE
Let `empty` target cells with no data

### PR DESCRIPTION
**Pull request by bartaelterman**
The documentation states that the optional property `empty` of the `legendColors` sets the color for dates with value == 0. This is confusing because the documentation also states that the property name `empty` of the `subDomainTitleFormat` targets dates without a value (so value == null).

So does `empty` target value == 0 or value == null?

I would encourage the latter option. In the case of the first option, there is a value which can be colored with the default legend and it makes more sense to do so. Furthermore, there is currently no way to color dates where value == null, which happens to be what I'm currently trying to accomplish.

I updated the code, but I get some failing unit tests. (I also get these before my modifications, so I assume I can ignore them).

### CODE REVIEW

**Comment by bartaelterman** [comment]
Using cal-heatmap again and ran into the same issue. Not all dates are included in my calendar, and for those dates, I want to specify their color using the `empty` option on the `legendColors` parameter. However, this does not work. The fix in this pull request solves the issue.

To make it more concrete, my calendar definition looks like this:

```
        yearcal = new CalHeatMap();
        yearcal.init({
            domain: "month",
            subDomain: "day",
            itemName: ['kilometer', 'kilometers'],
            domainGutter: 5,
            displayLegend: false,
            cellSize: 14,
             legendColors: {
                min: "#DAE289",
                max: "#3B6427",
                empty: "#dddddd"
            }, 
            tooltip: true,
            itemSelector: "#year-chart",
            previousSelector: "#previous-month",
            nextSelector: "#next-month",
            start: new Date(timestampFirstDate * 1000),
            range: 12,
            data: yeardata
        });
```

If I remove the entire `legendColors` attribute, the calendar is rendered properly. Cells with no value are grey, cells with data are colored using the default greenish legend colors.

But I want to modify the grey (because I need a little bit more contrast with my background, so I target that color using the `legendColors` attribute. The problem is, cells with no value (neither the timestamp nor the value is present in the yeardata object), are now colored  "#DAE289" (the color set by `min`). It looks like these cells are treated as value 0, although `considerMissingDataAsZero` is not set to true. Setting this value explicitly to false does not solve the issue.

The problem is this line:

```
if (d.v === 0 && options.legendColors !== null && options.legendColors.hasOwnProperty("empty")) {
```

This says that if the value is 0 and `legendColors` are specified and the `empty` attribute is given, the color of the cell needs to be set to the value given with `empty`. It explains why my calendar renders correctly when I don't set the `legendColors` attribute.

But the if statement is not correct. The `empty` flag should target cells where the value is `null` not where it is 0. So this should be:

```
if (d.v === null && options.legendColors !== null && options.legendColors.hasOwnProperty("empty")) {
```

And that is what this pull request does.

@kamisama could you please accept this change or tell me what I'm doing wrong?

**Comment by kamisama** [comment]
Hi back,

It took me some time to review the code, since I haven't touched it for months.
The fix seems logic, can you please edit the file in /src instead ? The files in the root are built by a grunt task.

**Comment by bartaelterman** [comment]
Thanks a lot! Will do so soon.

**Comment by kamisama** [comment]
What happens when the value is null, but `empty` is not set ? See #117

**Comment by bartaelterman** [comment]
When `legendColors` is set, but it had no attribute `empty`, a cell with value `null` is colored according to the color set in `legendColors.min`. This also happens on the current master version of cal-heatmap (I mean, that issue existed before my fix).
I'll see if I can add a fix for that too.

**Comment by bartaelterman** [comment]
While testing, I also notice that the `base` attribute is not working as advertised. For some reason, it gets overridden by the `min` color of `legendColors`.
So if I define `legendColors` with a `min`, `max` and `base` color, then cells with value `null` should be colored according to `base` and cells with value `0` should be colored according to `min`, right? As far as I can see it now, everything is colored according to `min`.
What kind of cells should be colored by `base`?

**Comment by bartaelterman** [comment]
As far as I can see, `base` is not really doing anything. It gets overridden by `min`. Furthermore, with my proposition to let the `empty` attribute target cells where `value === null`, there is no way to target cells where `value === 0` which could be what other users are looking for.

I propose the following:

the label `empty` will be replaced by the label `zero` and will target cells where the value is 0.
the label `base` will target cells where there is no data (value === null).

Could you agree with that?

**Comment by kamisama** [comment]
I agree that the `legendColors` option is a mess. It was added in order to re-color the entire calendar without any css changes, but there's some naming issue there.

#### Point 1

That makes more sense.

#### Point 2

`base` is the base color of the calendar (either because there is no data, or because they're not fetched yet). It's the default color for cells with `value == null`, and its goal is to be overridden by other color.
I think that is already the case now.

**Comment by kamisama** [comment]
Can you revert the changes in the 2 js files in the root folder, and only keep the edit in the js file located in the src folder ?

Files in the root are automatically built, and there's a conflict preventing the merge.

**Comment by bartaelterman** [comment]
@kamisama done

**Comment by joshuapinter** [comment]
@bartaelterman Just wanted to say a quick thank you for sorting this out. Was driving me mad that `base` and `empty` weren't doing _anything_, let alone what they were supposed to do.

Also, the docs are still referencing version `3.3.10` in the [Installation section](http://cal-heatmap.com/#installation). That threw me for a loop as well.

**Pull request merged**
